name: sweep-collab
method: bayes  # 'random' or 'grid' are alternatives
metric:
  name: val_top_1_accuracy
  goal: maximize

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 0.001
    max: 0.01
  weight_decay:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-3
  momentum:
    values: [0.92, 0.94, 0.96]
  batch_size:
    values: [256, 384, 512]
  val_split:
    values: [0.1]
  epochs:
    value: 10
  num_workers:
    value: 4


early_terminate:
  type: hyperband
  min_iter: 5

command:
  - python
  - train.py
